# Assignment 1: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [2]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[9.26088109e-01, 5.42489144e-01, 8.24491285e-01, 9.59202793e-01,
        2.52377476e-01, 3.20875347e-01, 9.46959213e-01, 7.21902506e-02,
        8.70716164e-01, 4.16226598e-01],
       [1.88410701e-01, 8.75860618e-01, 4.78051025e-01, 5.74585001e-01,
        7.11153498e-01, 8.74661764e-02, 2.90619098e-01, 2.12631437e-01,
        5.49928393e-01, 9.26452345e-01],
       [1.70433924e-01, 7.56734111e-01, 3.40232622e-02, 5.83218578e-01,
        2.42580401e-01, 7.18063111e-01, 7.86604237e-02, 1.13639424e-01,
        1.44962556e-01, 7.35556185e-01],
       [7.52961123e-01, 4.32326753e-01, 8.90146545e-01, 8.94083527e-01,
        6.03284718e-01, 5.90930857e-01, 5.11806341e-01, 2.05907181e-01,
        6.59230362e-01, 4.83278454e-02],
       [8.88682250e-01, 7.63243445e-01, 7.45415342e-01, 9.88157239e-01,
        7.18921999e-01, 6.93989126e-01, 3.44495605e-04, 1.31425493e-01,
        9.27789889e-01, 5.86041400e-01],
       [9.60381863e-01, 9.47208222e-01, 4.60402113e-01, 5.66201874e-01,
   

In [3]:
#3.3: return only the odd rows of A
#if index starts at 0:
A[1::2,:]
#if index starts with 1:
#A[::2,:]

array([[0.1884107 , 0.87586062, 0.47805103, 0.574585  , 0.7111535 ,
        0.08746618, 0.2906191 , 0.21263144, 0.54992839, 0.92645234],
       [0.75296112, 0.43232675, 0.89014655, 0.89408353, 0.60328472,
        0.59093086, 0.51180634, 0.20590718, 0.65923036, 0.04832785],
       [0.96038186, 0.94720822, 0.46040211, 0.56620187, 0.38897775,
        0.61911353, 0.55814629, 0.88683818, 0.89074291, 0.83391   ],
       [0.83312765, 0.96524215, 0.21378033, 0.78856532, 0.26152229,
        0.31552672, 0.39414483, 0.26531259, 0.73664156, 0.87623254],
       [0.34889275, 0.14522363, 0.26814421, 0.52283561, 0.04220844,
        0.95477033, 0.09900603, 0.71429801, 0.04516157, 0.8531146 ]])

In [4]:
#3.4: perform a matrix multiplication of A with it's transposed
A_transpose = A.transpose()
A*A_transpose

array([[8.57639185e-01, 1.02210760e-01, 1.40521285e-01, 7.22242412e-01,
        2.24283383e-01, 3.08162863e-01, 3.17746370e-01, 6.01436938e-02,
        2.28362237e-02, 1.45218442e-01],
       [1.02210760e-01, 7.67131822e-01, 3.61757518e-01, 2.48408468e-01,
        5.42783246e-01, 8.28486815e-02, 1.30435252e-01, 2.05240825e-01,
        2.25851128e-01, 1.34542777e-01],
       [1.40521285e-01, 3.61757518e-01, 1.15758237e-03, 5.19150002e-01,
        1.80823152e-01, 3.30597774e-01, 4.34663187e-02, 2.42938734e-02,
        3.90303435e-02, 1.97235134e-01],
       [7.22242412e-01, 2.48408468e-01, 5.19150002e-01, 7.99385352e-01,
        5.96140162e-01, 3.34586159e-01, 1.92606871e-01, 1.62371262e-01,
        1.77443406e-01, 2.52675185e-02],
       [2.24283383e-01, 5.42783246e-01, 1.80823152e-01, 5.96140162e-01,
        5.16848840e-01, 2.69946332e-01, 6.11989644e-05, 3.43706956e-02,
        2.12162504e-01, 2.47358935e-02],
       [3.08162863e-01, 8.28486815e-02, 3.30597774e-01, 3.34586159e-01,
   

In [5]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)

array([[-0.13791363,  1.19759138, -2.2449367 ,  0.33212528, -1.10670541,
         0.85007201, -1.09983224,  1.39288272, -1.00311646,  1.25148588],
       [ 0.19824432, -1.89852886,  2.87578414, -1.38931894,  1.96871761,
         0.44870354,  2.23055188, -1.61402994, -0.08888711, -2.44152837],
       [ 1.80353251, -1.53067639,  2.01355567, -3.11542302,  3.55986741,
         0.32156076,  2.70333263, -3.8073726 , -0.32587756, -1.65708416],
       [-1.64010656, -1.38096119,  0.27583843,  2.26352059, -0.14294609,
        -2.71967542,  0.9228414 ,  2.95296521,  0.83537133, -0.07189479],
       [-1.54481481,  3.65635898, -3.15676077,  3.21048428, -3.63439191,
         0.5139439 , -3.09515387,  2.24871384, -0.43958047,  2.22202107],
       [ 0.74670454,  0.15856264,  0.80568229, -0.31903863, -0.21756829,
         1.08044159, -0.94217012, -1.52480562, -0.07477383,  0.36025338],
       [ 0.53832597,  1.63644452, -0.81186477,  1.26078501, -2.72461732,
         0.66119549, -1.64260812,  0.47549957

In [6]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
np.where(A > 0.5, A*0.5, A)

array([[4.63044054e-01, 2.71244572e-01, 4.12245643e-01, 4.79601396e-01,
        2.52377476e-01, 3.20875347e-01, 4.73479607e-01, 7.21902506e-02,
        4.35358082e-01, 4.16226598e-01],
       [1.88410701e-01, 4.37930309e-01, 4.78051025e-01, 2.87292500e-01,
        3.55576749e-01, 8.74661764e-02, 2.90619098e-01, 2.12631437e-01,
        2.74964197e-01, 4.63226172e-01],
       [1.70433924e-01, 3.78367056e-01, 3.40232622e-02, 2.91609289e-01,
        2.42580401e-01, 3.59031556e-01, 7.86604237e-02, 1.13639424e-01,
        1.44962556e-01, 3.67778092e-01],
       [3.76480561e-01, 4.32326753e-01, 4.45073273e-01, 4.47041763e-01,
        3.01642359e-01, 2.95465429e-01, 2.55903171e-01, 2.05907181e-01,
        3.29615181e-01, 4.83278454e-02],
       [4.44341125e-01, 3.81621723e-01, 3.72707671e-01, 4.94078620e-01,
        3.59460999e-01, 3.46994563e-01, 3.44495605e-04, 1.31425493e-01,
        4.63894944e-01, 2.93020700e-01],
       [4.80190931e-01, 4.73604111e-01, 4.60402113e-01, 2.83100937e-01,
   